import type { Locale } from '../../i18n/locale'

export const beatIds = ['card', 'layers', 'compute', 'memory', 'power', 'contact', 'heatpipes', 'airflow', 'display'] as const
export type BeatId = typeof beatIds[number]
export type Beat = { label: string; title: string; body: string; look: string; action: string; detail: string; scene: string; source: number; image: string }
type Copy = {
  title: string; description: string; name: string; subtitle: string; back: string; chapters: string; previous: string;
  look: string; notes: string; reading: string; return: string; options: string; motion: string; reduced: string; model: string;
  loading: string; failed: string; retry: string; controls: string; close: string; turn: string; zoom: string; separate: string; reset: string;
  source: string; modelNote: string; schematic: string; replay: string; labels: Record<string, string>; beats: Beat[];
}
export const copy: Record<Locale, Copy> = {
  en: {
    title: 'One Frame — How a graphics card works', description: 'Open a graphics card, find its processor and memory, and follow the heat out. A guided exploration of the actual 3D parts.',
    name: 'One Frame', subtitle: 'Inside a graphics card', back: 'All stories', chapters: 'Choose a part', previous: 'Previous view',
    look: 'On the model', notes: 'More detail & sources', reading: 'Read the whole story', return: 'Return to the model', options: 'Reading & motion', motion: 'Reduce motion', reduced: 'Motion reduced', model: 'AXIOM 320 · An illustrative graphics card',
    loading: 'Preparing the graphics card…', failed: 'The 3D model could not open. This original render and every explanation are still available.', retry: 'Retry 3D', controls: 'Inspect the model', close: 'Close controls', turn: 'Turn', zoom: 'Zoom', separate: 'Separate layers', reset: 'Restore guided view', source: 'Reference', modelNote: 'AXIOM 320 is a fictional card. Its eight memory packages, six heatpipes and three fans come from the authored model. Board traces, internal electronics and thermal performance are illustrative.', schematic: 'Simplified paths · not a simulation', replay: 'Replay the demonstration',
    labels: { fans: 'Three fans', cooler: 'Metal heatsink', board: 'Circuit board', gpu: 'GPU die', memory: 'Video memory · 8 chips', connector: 'Power from the power supply', regulator: 'Voltage regulators', paste: 'Thermal paste', plate: 'Contact plate', pipes: 'Six heatpipes', fins: 'Thin metal fins', ports: 'Display connections' },
    beats: [
      { label: 'The complete card', title: 'What’s inside a\ngraphics card?', body: 'A graphics card builds the images on your screen. The fans are easy to spot, but the chip doing the calculations is hidden underneath. Let’s open the card and find it.', look: 'Start with the three fans. They belong to the cooling system.', action: 'Open the card', detail: 'A graphics card combines a processor, local memory, power circuits, cooling and display connections on one board. This is an original fictional design, not a specific retail product or a repair guide.', scene: 'The complete graphics card, shown from the fan side.', source: 0, image: 'assembled' },
      { label: 'Under the cover', title: 'Most of this card\nis here to cool it.', body: 'The outer cover holds the fans above a block of thin metal fins. Below that cooler is the circuit board. The processor and memory stay attached to this board when the cooler lifts away.', look: 'Follow the layers down: fans, heatsink, then the green circuit board.', action: 'Find the processor', detail: 'The backplate supports and covers the rear of the board. Screws hold the assembly together. The separated view shows how the parts fit; operating parts normally sit together, with thermal materials filling contact gaps.', scene: 'The cover, fans, cooler, board and backplate are separated, with labels on the cooling module and board.', source: 2, image: 'exploded' },
      { label: 'The processor', title: 'This small chip\ncalculates the image.', body: 'Imagine turning the camera in a game. The graphics processor, or GPU, works out where objects appear and helps calculate the colours you see. It handles many pieces of that work in parallel.', look: 'The blue square is the GPU die: the exposed piece of silicon. Its green base connects it to the board.', action: 'Find its memory', detail: 'GPU means graphics processing unit. In a typical rendering pipeline, geometry is transformed into the camera’s view, triangles are mapped to screen locations, and shading computes appearance. Those internal circuits are not modeled here.', scene: 'A close-up of the blue GPU die and its green package, with the surrounding board for context.', source: 0, image: 'board' },
      { label: 'The memory', title: 'The chip needs\ndata close by.', body: 'A game’s brick wall needs a texture: the data describing its surface. Video memory holds those surface details, object shapes and images being built. The GPU reads that data while it builds the image.', look: 'The eight dark chips around the GPU are video memory. The highlighted path shows one memory read.', action: 'Follow the power', detail: 'The line is a simplified data connection, not an actual trace. Real connections run through multiple board layers. Capacity tells you how much fits; bandwidth tells you how quickly it moves. Eight packages do not imply a particular capacity or speed.', scene: 'The GPU surrounded by eight highlighted memory packages. A schematic path connects one memory chip to the GPU.', source: 0, image: 'board' },
      { label: 'The power circuits', title: 'Stable power\nfor a tiny chip.', body: 'Power enters through the cable connector and the motherboard slot. The regulator circuits lower and control the voltage for the processor. Their repeated stages share the electrical load.', look: 'Find the black power socket, then the rows of grey blocks beside the GPU. These blocks are inductors in the regulator circuits.', action: 'Look under the cooler', detail: 'Switching components, inductors and capacitors work together to regulate voltage. The highlighted route explains their relationship, not the actual board wiring. This model has ten illustrative regulator stages; it does not specify a real power rating.', scene: 'The board with the power connector and regulator rows identified. A schematic power path runs toward the GPU.', source: 3, image: 'board' },
      { label: 'The thermal contact', title: 'Heat needs a way\nout of the chip.', body: 'The processor gets hot as it works. A metal contact plate sits against it, with a thin layer of thermal paste between them. Heat passes through that contact into the cooler.', look: 'These surfaces normally touch. They are pulled apart here so you can see the paste between the die and the plate.', action: 'Follow the heatpipes', detail: 'Thermal paste improves contact across tiny surface irregularities. Memory and power components use thermal pads where their heights differ. This view isolates the GPU contact; it does not model temperatures or microscopic surface roughness.', scene: 'An enlarged, separated stack of GPU package, thermal paste and metal contact plate.', source: 4, image: 'cooler' },
      { label: 'The heatpipes', title: 'Six pipes spread\nheat across the cooler.', body: 'The chip heats a small area. The heatpipes carry that heat into a much wider set of metal fins. Inside each sealed pipe, a fluid evaporates at the hot end and condenses where it is cooler.', look: 'The fin banks are faded so you can trace the six real pipes from the contact plate through the cooler.', action: 'See how the fans help', detail: 'A wick inside a typical heatpipe returns liquid toward the warm region. The model shows the pipe exteriors, not their internal fluid. The fins provide a large area where heat can pass into moving air.', scene: 'The cooler viewed from below. Six highlighted heatpipes remain solid while the fin banks fade to reveal their routes.', source: 5, image: 'cooler' },
      { label: 'The moving air', title: 'The fans carry\nthe heat away.', body: 'The fins warm the air touching them. The fans keep that air moving through the gaps, replacing it with cooler air. That lets the cooler keep taking heat from the chip.', look: 'Watch the actual fan blades turn. The arrows show a simplified direction of airflow through the fins.', action: 'Find the display sockets', detail: 'Fan rotation here is slowed down for inspection. The arrows explain the cooling idea; they are not a fluid simulation. Cooling operates continuously while the card works, not as a separate step after each image.', scene: 'Three fans above the finned heatsink, with a brief rotation demonstration and schematic airflow arrows.', source: 2, image: 'assembled' },
      { label: 'To the screen', title: 'The finished image\nleaves through here.', body: 'The card sends the image through a display connection to your monitor. The processor calculates, memory supplies data, power circuits feed them, and cooling keeps heat moving out. All of these parts work together.', look: 'These sockets at the end of the board are the display outputs. This design has three DisplayPort sockets and one HDMI socket.', action: 'Put the card back together', detail: 'Rendering and display refresh have separate timing. A 60 Hz display refreshes about every 16.7 ms, but that does not guarantee the card produces 60 new images each second. These port shapes are illustrative.', scene: 'A close-up of the four output sockets at the end of the graphics card.', source: 1, image: 'assembled' },
    ],
  },
  fr: {
    title: 'Une image — Comment fonctionne une carte graphique', description: 'Ouvrez une carte graphique, repérez son processeur et sa mémoire, puis suivez la chaleur vers l’extérieur. Une exploration guidée des pièces en 3D.',
    name: 'Une image', subtitle: 'Dans une carte graphique', back: 'Tous les récits', chapters: 'Choisir une pièce', previous: 'Vue précédente',
    look: 'Sur le modèle', notes: 'Détails et sources', reading: 'Lire tout le récit', return: 'Revenir au modèle', options: 'Lecture et mouvement', motion: 'Réduire le mouvement', reduced: 'Mouvement réduit', model: 'AXIOM 320 · Une carte graphique illustrative',
    loading: 'Préparation de la carte graphique…', failed: 'Le modèle 3D est indisponible. Ce rendu original et toutes les explications restent accessibles.', retry: 'Réessayer la 3D', controls: 'Examiner le modèle', close: 'Fermer les commandes', turn: 'Tourner', zoom: 'Zoomer', separate: 'Séparer les couches', reset: 'Rétablir la vue guidée', source: 'Référence', modelNote: 'AXIOM 320 est une carte fictive. Ses huit boîtiers mémoire, six caloducs et trois ventilateurs proviennent du modèle original. Pistes, électronique interne et performances thermiques sont illustratives.', schematic: 'Trajets simplifiés · sans simulation', replay: 'Revoir la démonstration',
    labels: { fans: 'Trois ventilateurs', cooler: 'Dissipateur métallique', board: 'Circuit imprimé', gpu: 'Puce graphique', memory: 'Mémoire vidéo · 8 puces', connector: 'Depuis l’alimentation', regulator: 'Régulateurs de tension', paste: 'Pâte thermique', plate: 'Plaque de contact', pipes: 'Six caloducs', fins: 'Fines ailettes métalliques', ports: 'Sorties vidéo' },
    beats: [
      { label: 'La carte complète', title: 'Que contient une\ncarte graphique ?', body: 'Une carte graphique construit les images à l’écran. Les ventilateurs sont bien visibles, mais la puce qui fait les calculs se cache dessous. Ouvrons la carte pour la trouver.', look: 'Repérez les trois ventilateurs. Ils font partie du refroidissement.', action: 'Ouvrir la carte', detail: 'Une carte graphique réunit un processeur, de la mémoire locale, des circuits d’alimentation, du refroidissement et des sorties vidéo. Ce modèle fictif original ne représente pas un produit commercial ni une procédure de réparation.', scene: 'La carte graphique complète, vue du côté des ventilateurs.', source: 0, image: 'assembled' },
      { label: 'Sous la coque', title: 'Une grande partie\nsert à refroidir.', body: 'La coque maintient les ventilateurs au-dessus d’un bloc de fines ailettes métalliques. Le circuit imprimé se trouve sous ce dissipateur. Le processeur et la mémoire restent fixés au circuit lorsque le refroidisseur se soulève.', look: 'Suivez les couches : ventilateurs, dissipateur, puis circuit imprimé vert.', action: 'Trouver le processeur', detail: 'La plaque arrière protège et soutient le circuit. Des vis maintiennent l’ensemble. La vue éclatée explique l’assemblage ; en fonctionnement, les surfaces sont rapprochées et des matériaux thermiques comblent les contacts.', scene: 'Coque, ventilateurs, dissipateur, circuit et plaque arrière séparés, avec des repères sur les pièces principales.', source: 2, image: 'exploded' },
      { label: 'Le processeur', title: 'Cette petite puce\ncalcule l’image.', body: 'Imaginez que vous tournez la caméra dans un jeu. Le processeur graphique détermine où apparaissent les objets et participe au calcul de leurs couleurs. Il traite de nombreuses opérations en parallèle.', look: 'Le carré bleu est la puce graphique : le silicium exposé. Sa base verte la relie au circuit imprimé.', action: 'Trouver sa mémoire', detail: 'GPU signifie processeur graphique. Pour un rendu classique, la géométrie est transformée selon la caméra, les triangles sont associés à des positions à l’écran et les calculs d’ombrage déterminent leur apparence. Ces circuits internes ne sont pas représentés.', scene: 'Gros plan de la puce bleue et de son support vert, avec le circuit environnant.', source: 0, image: 'board' },
      { label: 'La mémoire', title: 'Il faut des données\nà portée de la puce.', body: 'Un mur de briques dans un jeu utilise une texture : des données décrivant sa surface. La mémoire vidéo stocke ces détails de surface, les formes des objets et les images en construction. Le processeur y lit les données pour construire l’image.', look: 'Les huit boîtiers sombres autour du processeur sont la mémoire vidéo. Le trajet coloré montre une lecture mémoire.', action: 'Suivre l’alimentation', detail: 'Le trait est une liaison simplifiée, pas une piste réelle. Les connexions passent par plusieurs couches du circuit. La capacité indique la quantité stockable ; la bande passante, la vitesse de transfert. Huit boîtiers ne définissent ni capacité ni vitesse.', scene: 'Le processeur entouré de huit boîtiers mémoire mis en évidence. Une liaison schématique relie un boîtier au processeur.', source: 0, image: 'board' },
      { label: 'L’alimentation', title: 'La puce a besoin\nd’une tension stable.', body: 'L’énergie arrive par le connecteur du câble et le port de la carte mère. Les circuits régulateurs abaissent et contrôlent la tension fournie au processeur. Leurs étages répétés se partagent la charge électrique.', look: 'Repérez la prise noire, puis les rangées de blocs gris près du processeur : les inductances des régulateurs.', action: 'Regarder sous le refroidisseur', detail: 'Composants de commutation, inductances et condensateurs régulent ensemble la tension. Le trajet coloré explique leur relation, pas le câblage réel. Ce modèle possède dix étages illustratifs, sans puissance nominale réelle.', scene: 'Le circuit avec le connecteur d’alimentation et les régulateurs repérés. Un trajet simplifié mène au processeur.', source: 3, image: 'board' },
      { label: 'Le contact thermique', title: 'La chaleur doit\nquitter la puce.', body: 'En travaillant, le processeur chauffe. Une plaque métallique est plaquée contre lui, avec une fine couche de pâte thermique entre les deux. La chaleur passe par ce contact vers le refroidisseur.', look: 'Ces surfaces se touchent normalement. Elles sont séparées ici pour montrer la pâte entre la puce et la plaque.', action: 'Suivre les caloducs', detail: 'La pâte améliore le contact malgré les petites irrégularités des surfaces. Des tampons thermiques relient les composants mémoire et d’alimentation de hauteurs différentes. Les températures et les rugosités microscopiques ne sont pas simulées.', scene: 'Vue rapprochée et éclatée du processeur, de la pâte thermique et de la plaque de contact métallique.', source: 4, image: 'cooler' },
      { label: 'Les caloducs', title: 'Six tubes répartissent\nla chaleur.', body: 'La puce chauffe une petite surface. Les caloducs transportent cette chaleur vers les ailettes, bien plus étendues. Dans chaque tube scellé, un fluide s’évapore du côté chaud et se condense du côté plus froid.', look: 'Les ailettes sont estompées pour révéler les six tubes réels, de la plaque de contact au reste du dissipateur.', action: 'Voir le rôle des ventilateurs', detail: 'Une structure capillaire interne ramène le liquide vers la zone chaude. Le modèle montre l’extérieur des tubes, pas leur fluide. Les ailettes offrent une grande surface pour transférer la chaleur à l’air en mouvement.', scene: 'Dessous du refroidisseur : six caloducs visibles à travers les ailettes estompées.', source: 5, image: 'cooler' },
      { label: 'L’air en mouvement', title: 'Les ventilateurs\névacuent la chaleur.', body: 'Les ailettes réchauffent l’air qui les touche. Les ventilateurs font circuler cet air dans les espaces et le remplacent par de l’air plus frais. Le refroidisseur peut ainsi continuer à absorber la chaleur de la puce.', look: 'Observez les pales réelles tourner. Les flèches indiquent un sens simplifié de circulation à travers les ailettes.', action: 'Trouver les sorties vidéo', detail: 'La rotation est ralentie pour être observable. Les flèches expliquent le principe, sans simulation des fluides. Le refroidissement est continu pendant le travail de la carte, pas une étape après chaque image.', scene: 'Trois ventilateurs au-dessus des ailettes, avec une courte rotation et des flèches schématiques de circulation d’air.', source: 2, image: 'assembled' },
      { label: 'Vers l’écran', title: 'L’image terminée\nsort par ici.', body: 'La carte transmet l’image au moniteur par une sortie vidéo. Le processeur calcule, la mémoire fournit les données, les circuits les alimentent et le refroidissement évacue la chaleur. Toutes ces pièces travaillent ensemble.', look: 'Ces prises au bout du circuit sont les sorties vidéo : trois DisplayPort et une HDMI sur ce modèle.', action: 'Réassembler la carte', detail: 'Rendu et rafraîchissement ont des cadences distinctes. Un écran à 60 Hz se rafraîchit environ toutes les 16,7 ms, sans garantir que la carte produise 60 nouvelles images par seconde. Les formes des ports sont illustratives.', scene: 'Gros plan des quatre sorties vidéo au bout de la carte graphique.', source: 1, image: 'assembled' },
    ],
  },
}
export const sources = [
  { title: 'NVIDIA · Graphics Pipeline Performance', url: 'https://developer.nvidia.com/gpugems/gpugems/part-v-performance-and-practicalities/chapter-28-graphics-pipeline-performance' },
  { title: 'Intel · Frame pacing & display refresh', url: 'https://www.intel.com/content/www/us/en/developer/articles/technical/xess2-whitepaper.html' },
  { title: 'NVIDIA · Cooling assembly reference', url: 'https://www.nvidia.com/content/PDF/kepler/tesla-k20-active-bd-06499-001-v03.pdf' },
  { title: 'Texas Instruments · Multiphase processor power', url: 'https://www.ti.com/product-category/power-management/multiphase.html' },
  { title: 'Noctua · Thermal contact & paste performance', url: 'https://www.noctua.at/en/expertise/tech/performance-comparison-nt-h1-vs-nt-h2' },
  { title: 'Boyd · Heat pipe technology', url: 'https://info.boydcorp.com/hubfs/Thermal/Two-Phase-Cooling/Boyd-Heat-Pipes-Brochure.pdf' },
]
